add_rules("mode.debug", "mode.release")
target("triangle")
    -- set_kind("object")
    set_kind("static")
    -- set_languages("c++latest")
    add_includedirs("$(projectdir)/include", "$(projectdir)/external/eigen")
    add_files("src/triangle/*.cpp")
    add_defines("TRILIBRARY", "ANSI_DECLARATORS", "REAL=double", "VOID=int", "_USE_MATH_DEFINES")
    if is_plat("windows") then
        add_defines("NO_TIMER")
    end
    set_warnings("everything")
    -- set_toolset("ar", "llvm-ar.exe")
    add_cxxflags("-Wno-c++98-compat")
target("predicates")
    set_kind("static")
    -- set_languages("clatest")
    add_includedirs("$(projectdir)/include")
    add_files("src/predicates/predicates.c")
    -- set_toolset("ar", "llvm-ar.exe")

target("geometry")
    set_kind("binary")
    add_deps("triangle", "predicates")
    add_files("src/*.cpp")
    set_warnings("everything")
    add_includedirs("$(projectdir)/include", "$(projectdir)/external/eigen")
    add_cxxflags("-Wno-c++98-compat")
